<?php

# HABILITAR DETALHES DOS ERROS
putenv("DISPLAY_ERRORS_DETAILS=" . true);

# CONEXAO COM BANCO DE DADOS MYSQL - codeeasy_gerenciador_de_lojas
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_HOST=localhost");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_DBNAME=codeeasy_gerenciador_de_lojas");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_USER=root");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PASSWORD=");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PORT=3306");