<?php

# HABILITAR DETALHES DOS ERROS
putenv("DISPLAY_ERRORS_DETAILS=" . false);

# CONEXAO COM BANCO DE DADOS MYSQL
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_HOST=");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_DBNAME=");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_USER=");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PASSWORD=");
putenv("CODEEASY_GERENCIADOR_DE_LOJAS_MYSQL_PORT=");